name: CI
# description: Continuous Integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run-code-quality:
        description: 'Check code quality?'
        required: false
        type: boolean
        default: false
      run-image-scan:
        description: 'Scan container image?'
        required: false
        type: boolean
        default: false

concurrency:
  group: "${{ github.ref }}-ci"
  cancel-in-progress: true

jobs:
  git-check:
    name: Git
    uses: ./.github/workflows/reusable-git-check.yml
    with:
      is-pull-request: ${{ github.event_name == 'pull_request' }}

  content-validate:
    name: Markup
    uses: devpro/github-workflow-parts/.github/workflows/reusable-markup-lint.yml@af83b76db469841ad5d7a1c102d41d9e3bc147ea

  code-quality:
    name: Code
    needs: git-check
    if: needs.git-check.outputs.app_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.run-code-quality)
    uses: devpro/github-workflow-parts/.github/workflows/reusable-dotnet-quality.yml@af83b76db469841ad5d7a1c102d41d9e3bc147ea
    with:
      custom-commands: |
        dotnet build --no-restore --configuration Debug test/BlazorApp.PlaywrightTests
        pwsh test/BlazorApp.PlaywrightTests/bin/Debug/net10.0/playwright.ps1 install --with-deps
      extra-vars: |
        Application__IsHttpsRedirectionEnabled="false"
      mongodb-enabled: true
      fossa-enabled: true
      sonar-enabled: true
      sonar-organization: ${{ vars.SONAR_ORG }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: Todo Blazor
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
      pull-requests: write

  image-scan:
    name: Image
    needs: git-check
    if: needs.git-check.outputs.app_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.run-image-scan)
    uses: devpro/github-workflow-parts/.github/workflows/reusable-container-scan.yml@af83b76db469841ad5d7a1c102d41d9e3bc147ea
    with:
      image-definition: "src/BlazorApp/Dockerfile"
      image-name: ${{ vars.CONTAINER_IMAGE_NAME }}
      image-path: ${{ vars.CONTAINER_REGISTRY_PATH }}
      image-tag: "${{ needs.git-check.outputs.version_major_minor }}.${{ github.run_id }}"
